name: varsusage

on:
  workflow_dispatch:
    inputs:
      environment:
        default: 'prod'
        required: true
        type: 'string'
jobs:
  build:
    uses: ./.github/workflows/reusable.yml
    with:
      host: ${{ vars.TEST_RES_SECRET }}
    secrets: inherit
